pipeline:
  identifier: Build_net_me_challenge_api_1699621368012
  name: Build net-me-challenge-api
  orgIdentifier: default
  projectIdentifier: HABITVS
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1699621352125
        repoName: net-me-challenge-api
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushACR
                  name: BuildAndPushACR_1
                  identifier: BuildAndPushACR_1
                  spec:
                    connectorRef: Azure_Cloud
                    repository: habitvsdev.azurecr.io
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
