pipeline:
  identifier: Build_net_me_challenge_api_1699555790395
  name: Build net-me-challenge-api
  orgIdentifier: default
  projectIdentifier: StrokeReactApp
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1699555768138
        repoName: net-me-challenge-api
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
