pipeline:
  identifier: Build_net_me_challenge_api_1699622143547
  name: Build net-me-challenge-api
  orgIdentifier: default
  projectIdentifier: HABITVS
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1699622125770
        repoName: net-me-challenge-api
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushACR
                  name: BuildAndPushACR_1
                  identifier: BuildAndPushACR_1
                  spec:
                    connectorRef: Azure_Cloud
                    repository: habitvsdev.azurecr.io
                    subscriptionId: a0d83190-30b5-4713-982d-a65fda36ae92
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
