pipeline:
  identifier: Build_net_me_challenge_api_1699622143547
  name: Build net-me-challenge-api
  orgIdentifier: default
  projectIdentifier: HABITVS
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1699622125770
        repoName: net-me-challenge-api
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
